import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Tajawal } from "next/font/google";
import "./globals.css";
import NewsBar from "@/components/layout/NewsBar";
import { getNewsItems, getNewsSettings } from "@/lib/news";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["arabic"],
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const newsItems = await getNewsItems();
  const newsSettings = await getNewsSettings();

  const direction = newsSettings?.direction || "rtl"; // Default to rtl if not set
  const speedSeconds = newsSettings?.speed_seconds || 30; // Default speed

  return (
    <html lang="ar" dir={direction}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.className} antialiased`}
      >
        {newsItems.length > 0 && (
          <NewsBar
            newsItems={newsItems}
            direction={direction as "ltr" | "rtl"}
            speedSeconds={speedSeconds}
          />
        )}
        {children}
      </body>
    </html>
  );
}

